import base64
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build


def _build_gmail_service(access_token: str, refresh_token: Optional[str] = None):
    creds = Credentials(
        token=access_token,
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.getenv("GOOGLE_CLIENT_ID"),
        client_secret=os.getenv("GOOGLE_CLIENT_SECRET"),
        scopes=["https://www.googleapis.com/auth/gmail.send"],
    )
    return build("gmail", "v1", credentials=creds)


def send_plan_confirmation(
    access_token: str,
    refresh_token: Optional[str],
    to_email: str,
    user_name: str,
    plan_json: dict,
    frontend_url: str,
) -> str:
    """Send a confirmation email with the plan summary. Returns message ID."""
    service = _build_gmail_service(access_token, refresh_token)

    plan_title = plan_json.get("plan_title", "Your Workout Plan")
    summary = plan_json.get("summary", "")
    days = plan_json.get("days", [])
    duration = len(days)

    # Build HTML email
    day_rows = ""
    for day in days[:7]:  # Show first 7 days in email
        day_rows += f"""
        <tr style="border-bottom: 1px solid #eee;">
            <td style="padding: 8px 12px; font-weight: bold; color: #555;">Day {day['day']} — {day['date']}</td>
            <td style="padding: 8px 12px;">{day['title']}</td>
            <td style="padding: 8px 12px; color: #888;">{day['duration_minutes']} min</td>
        </tr>"""

    if duration > 7:
        day_rows += f"""
        <tr>
            <td colspan="3" style="padding: 8px 12px; color: #888; font-style: italic;">
                ... and {duration - 7} more days in your calendar
            </td>
        </tr>"""

    html_body = f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; color: #333; padding: 20px;">

    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; border-radius: 12px 12px 0 0; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 28px;">💪 Your Workout Plan is Ready!</h1>
        <p style="color: rgba(255,255,255,0.85); margin-top: 8px;">Time to crush your fitness goals, {user_name}!</p>
    </div>

    <div style="background: #fff; padding: 30px; border: 1px solid #e8e8e8; border-top: none;">
        <h2 style="color: #4a4a4a; margin-top: 0;">{plan_title}</h2>
        <p style="color: #666; line-height: 1.6;">{summary}</p>

        <div style="background: #f8f9fa; border-radius: 8px; padding: 20px; margin: 20px 0;">
            <p style="margin: 0; font-size: 14px; color: #555;">
                📅 <strong>{duration} days</strong> of workouts have been added to your Google Calendar<br>
                🔔 You'll receive reminders <strong>30 minutes before</strong> each workout
            </p>
        </div>

        <h3 style="color: #4a4a4a;">Your Schedule:</h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <thead>
                <tr style="background: #f0f0f0;">
                    <th style="padding: 10px 12px; text-align: left; color: #555;">Day</th>
                    <th style="padding: 10px 12px; text-align: left; color: #555;">Workout</th>
                    <th style="padding: 10px 12px; text-align: left; color: #555;">Duration</th>
                </tr>
            </thead>
            <tbody>{day_rows}</tbody>
        </table>

        <div style="text-align: center; margin-top: 30px;">
            <a href="{frontend_url}/dashboard"
               style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white; padding: 14px 32px; border-radius: 8px;
                      text-decoration: none; font-weight: bold; font-size: 16px;
                      display: inline-block;">
                View Your Full Plan →
            </a>
        </div>
    </div>

    <div style="padding: 20px; text-align: center; color: #aaa; font-size: 12px;">
        <p>Generated by Exercise Planner • Powered by Claude AI</p>
    </div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"💪 Your {duration}-Day Workout Plan: {plan_title}"
    msg["From"] = to_email
    msg["To"] = to_email
    msg.attach(MIMEText(html_body, "html"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()
    return sent["id"]
